name: Pact Plugin Driver (Gradle)

on:
  - push
  - pull_request

jobs:
  latest_jdk:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build plugin driver
        run: ./gradlew -s --no-daemon -i publishToMavenLocal
        working-directory: drivers/jvm
      - name: Install plugin cli
        run: scripts/install-plugin-cli.sh
        shell: bash
      - name: Install Protobuf plugin
        run: ~/bin/pact-plugin-cli -y install protobuf
        shell: bash
      - name: Run plugin driver tests
        run: ./gradlew -s --no-daemon -i check
        working-directory: drivers/jvm
      - name: Publish driver Pact file
        run: ./gradlew --no-daemon pactPublish
        env:
          GIT_SHA: $GITHUB_SHA
          ORG_GRADLE_PROJECT_pactBrokerToken: ${{ secrets.PACTFLOW_TOKEN }}
        working-directory: drivers/jvm
        if: runner.os == 'Linux'

  supported_jdks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11, 17, 19 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build plugin driver
        run: ./gradlew -s --no-daemon -i publishToMavenLocal
        working-directory: drivers/jvm
      - name: Install plugin cli
        run: scripts/install-plugin-cli.sh
        shell: bash
      - name: Install Protobuf plugin
        run: ~/bin/pact-plugin-cli -y install protobuf
        shell: bash
      - name: Run plugin driver tests
        run: ./gradlew -s --no-daemon -i check
        working-directory: drivers/jvm
